### ISSUE TITLE
Cant figure out how to disable toggle sneak, I remember enabling it but i cant disable bc I forgot where

### ISSUE THREAD

**Issue by ThisSharkPleyzYT** [My-Name-Is-Jeff/SimpleToggleSprint#9]
Pls Help T-T It got annoying to have toggle shift

**Comment by Benj2005** [comment]
Open the ToggleSprint options menu by using the `/togglesprint` command, then you can find the toggle sneak setting under General > Toggle Sneak (as shown).
![e037b555a9845013a1850f87b9922603](https://user-images.githubusercontent.com/62969241/189518442-e82934af-b978-4759-8c69-c6c186ecb153.PNG)
